plugins {
    id 'com.android.application'
}

android {
    namespace 'io.github.hara_om_25.battle_reports'
    compileSdk 34

    defaultConfig {
        applicationId 'io.github.hara_om_25.battle_reports'
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        debug {
            applicationIdSuffix ''
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.5.0'
}
